feat: create tag for context on log
YourSurpriseCom/monolog-dd-udp-handler pull request #14
Opened 2024-01-11 12:53 UTC by DjordyKoert

2024-01-11 12:56 UTC, DjordyKoert commented
maybe it makes more sense to create a new handler / package for this?

2024-01-11 13:22 UTC, Daniel-I-Am requested changes

2024-01-11 13:22 UTC, Daniel-I-Am commented on src/Handler/DataDogUdpHandler.php
> +                $rootSpan->setTag($key, $value);
Can you add a prefix here so we don't overlap with anything built-in?

Probably something like this:
```suggestion
                $rootSpan->setTag("monolog-context.$key", $value);
```

2024-01-11 13:22 UTC, Daniel-I-Am commented on src/Handler/DataDogUdpHandler.php
> +            $rootSpan = GlobalTracer::get()->getRootScope()?->getSpan();
Should this be added onto the root span? I'd prefer it to be the active span, so we don't go mixing logs between services and the like.

2024-01-12 10:20 UTC, Januznl approved these changes

2024-01-12 10:22 UTC, Daniel-I-Am approved these changes

2024-01-12 10:25 UTC, merged